### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/ms-job-service?createDatabaseIfNotExist=true
spring.application.name=ms-job-service
server.port=8082
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update