# ==============================
# SERVER
# ==============================
server.port=8081
spring.application.name=freelancer-profile-service

# ==============================
# DATABASE MySQL
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/trustedwork_freelancer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# SWAGGER
# ==============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ==============================
# JWT
# ==============================
jwt.secret=TrustedWorkSecretKey2024TunisiaESPRIT
jwt.expiration=86400000